[book]
authors = ["moyanjdc", "zhangxuan2011"]
language = "zh-CN"
src = "docs"
title = "Proka Kernel Documentation"

[output.html]
git-repository-url = "https://github.com/RainSTR-Studio/proka-kernel"
edit-url-template = "https://github.com/RainSTR-Studio/proka-kernel/edit/main/docs/{path}"
